[package]
name = "envcache"
license = "CC0-1.0"
version = "0.1.1"
authors = ["neil <neil.henning@hey.com>"]
edition = "2018"
repository = "https://github.com/sheredom/envcache"
description = "A build.rs helper crate for caching environment variables"
